<a href="https://colab.research.google.com/github/bhavya5463/DA-LAB/blob/da-lab/DA_LAB_NUMPY_2_ARRAY_OPERATIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([1,2,5,3,6])
print(a+1)
print(a-1)
print(a.ndim)

[2 3 6 4 7]
[0 1 4 2 5]
1


In [ ]:
a=np.array([[1,2],[4,6]])
print(a.ndim)
b=np.array([[1,6],[2,3]])
c=np.add(a,b)
print(c)
print("subtraction is:")
d=np.subtract(a,b)
print(d)
print("multiplication is:")
e=np.matmul(a,b)
print(e)

2
[[2 8]
 [6 9]]
subtraction is:
[[ 0 -4]
 [ 2  3]]
multiplication is:
[[ 5 12]
 [16 42]]


In [ ]:
#i)Create multi-dimensional arrays and find its shape and dimension
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.shape)
print(a.ndim)

(2, 2, 3)
3


In [ ]:
#ii)	Create a matrix full of zeros and ones 

a=np.zeros((2,4))
print(a)
b=np.ones((2,3))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#iii)	Reshape and flatten data in the array 
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print("after reshape")
b=np.reshape(a,(3,2))
print(b)
print("after reshape size is :",b.shape)

c=a.flatten()
print(c)
print(c.shape)

(2, 3)
after reshape
[[1 2]
 [3 4]
 [5 6]]
after reshape size is : (3, 2)
[1 2 3 4 5 6]
(6,)


In [ ]:
#iv)	Append data vertically and horizontally 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.hstack((a,b))
print(c)
d=np.vstack((a,b))
print(d)
print(np.append(a,b,axis=1))
print(np.append(a,b,axis=0))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#v)	Apply indexing and slicing on array 
a=np.array([1,2,3])
print("for 1D array index of a[2] is",a[2])
b=np.array([[1,2,3],[4,5,6]])
print("for 2D array index is",b[1,1])
c=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])
print("for multidimension array index is",c[1,0,1])

print("slicing")
a=np.array([1,2,3,4,5])
print(a[1])
print(a[1:-1])
print(a[:-1])

for 1D array index of a[2] is 3
for 2D array index is 5
for multidimension array index is 5
slicing
2
[2 3 4]
[1 2 3 4]


In [ ]:
#vi)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 
a=np.array([[1,2,3],[9,4,7]])
print("the maximum is:",np.amax(a))
print("the minimum is:",np.amin(a))
print("the mean is:",np.mean(a))
print("the median is:",np.median(a))
print("the standard deviation is:",np.std(a))
print("the vriance is:",np.var(a))

the maximum is: 9
the minimum is: 1
the mean is: 4.333333333333333
the median is: 3.5
the standard deviation is: 2.8087165910587863
the vriance is: 7.88888888888889


In [ ]:
#vii)	Dot and matrix product of two arrays 
a=np.array([[1,2],[4,5]])
b=np.array([[1,2],[4,5]])
print("dot of two arrays is:",np.dot(a,b))
print("matrix product:",a*b)

dot of two arrays is: [[ 9 12]
 [24 33]]
matrix product: [[ 1  4]
 [16 25]]


In [ ]:
#viii)	Compute the Eigen values of a matrix 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
eig_val,eig_ves=np.linalg.eig(a)
print("eigen values:",eig_val)

eigen values: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [ ]:
#ix)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 
a=[[3,1],[1,2]]
b=[9,8]
print(np.linalg.solve(a,b))

[2. 3.]


In [ ]:
#x)	Compute the multiplicative inverse of a matrix 
a=np.array([[1,2],[4,5]])
print(np.linalg.inv(a))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [ ]:
#xi)	Compute the rank of a matrix 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.matrix_rank(a))

2


In [ ]:
#xiiCompute the determinant of an array
a=np.array([[1,2,3],[10,6,3],[7,8,9]])
print(np.linalg.det(a))

6.000000000000001
