<a href="https://colab.research.google.com/github/bhavya5463/DA-LAB/blob/da-lab/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
arr1=np.array([5,2,3,4],dtype="i")
print(arr1)
print(arr1.dtype)

[5 2 3 4]
int32


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)
newarr=arr.astype("int16")
print(newarr.dtype)

int64
int16


In [ ]:
#1-D Dimension 
arr=np.arange(10)
print(arr)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
#2-D Dimensions
arr=np.arange(20).reshape(4,5)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [ ]:
print(np.zeros((2,4)))
print(np.ones((3,6)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
print(np.empty((2,1)))
print(np.full((1,2),100))

[[4.94e-322]
 [4.94e-322]]
[[100 100]]


In [ ]:
print(np.eye(5,5))
print(np.linspace(2,7,num=4))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[2.         3.66666667 5.33333333 7.        ]


In [ ]:
np.random.random((3,4))

array([[0.12290274, 0.33383126, 0.24263245, 0.07186229],
       [0.2820288 , 0.91207558, 0.74213476, 0.66570002],
       [0.13648132, 0.39781117, 0.56760957, 0.21866044]])

In [ ]:
a=np.array(10)
print(a)
print(a.ndim)
b=np.array([1,1,1])
print(b)
print(b.ndim)
print(b.shape)
c=np.array([[1,1,1],[2,2,2]])
print(c)
print(c.ndim)
print(c.shape)
d=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print(d)
print(d.ndim)
print(d.shape)

10
0
[1 1 1]
1
(3,)
[[1 1 1]
 [2 2 2]]
2
(2, 3)
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
3
(2, 2, 3)


In [ ]:
arr=np.array([1,1,1,1,1],ndmin=3)
print(arr)
print(arr.ndim)

[[[1 1 1 1 1]]]
3


In [ ]:
data=[[0.9876,-0.3456,-0.2456],[0.2578,0.6978,0.3654]]
data

[[0.9876, -0.3456, -0.2456], [0.2578, 0.6978, 0.3654]]

In [ ]:
data * 10

[[0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654],
 [0.9876, -0.3456, -0.2456],
 [0.2578, 0.6978, 0.3654]]