<a href="https://colab.research.google.com/github/bhavya5463/DA-LAB/blob/da-lab/numpy_tasks_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
wines=np.genfromtxt("/content/winequality-red.csv",delimiter=";",skip_header=1)
wines.dtype="float"
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
wines.shape

(1599, 12)

In [ ]:
wines[2,3]

2.3

In [ ]:
wines[:3,3]

array([1.9, 2.6, 2.3])

In [ ]:
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [ ]:
wines[3,:]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [ ]:
print(wines[1,5])
wines[1,5]=10
print(wines[1,5])

25.0
10.0


In [ ]:
new_slice=wines[:,9]
new_slice[:]=666
print(new_slice)
print(new_slice.shape)

[666. 666. 666. ... 666. 666. 666.]
(1599,)


In [ ]:
print(wines)

[[7.40e+00 7.00e-01 0.00e+00 ... 6.66e+02 9.40e+00 5.00e+00]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.66e+02 9.80e+00 5.00e+00]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.66e+02 9.80e+00 5.00e+00]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 6.66e+02 1.10e+01 6.00e+00]
 [5.90e+00 6.45e-01 1.20e-01 ... 6.66e+02 1.02e+01 5.00e+00]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.66e+02 1.10e+01 6.00e+00]]


In [ ]:
wines.dtype="int"
print(wines.dtype)

int64


In [ ]:
wines.dtype="float"
wines[:,11]+=10
print(wines[:,11])

[25. 25. 25. ... 26. 25. 26.]


In [ ]:
np.sum(wines)

1247931.40194

In [ ]:
np.sum(wines,axis=0)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [ ]:
b=np.sum(wines,axis=1)
print(b)

[ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]


In [ ]:
wines[:,11]+wines[:,11]

array([10., 10., 10., ..., 12., 10., 12.])

In [ ]:
wines[:,10]*wines[:,11]

array([47., 49., 49., ..., 66., 51., 66.])

In [ ]:
wines[:,11]>5

array([False, False, False, ...,  True, False,  True])

In [ ]:
wines[:,11]==10

array([False, False, False, ..., False, False, False])

In [ ]:
high_quality = wines[:,11] > 7
wines[high_quality,:]

array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 8.6000e-01,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 8.2000e-01,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 8.2000e-01,
        1.2900e+01, 8.0000e+00],
       [1.2600e+01, 3.1000e-01, 7.2000e-01, 2.2000e+00, 7.2000e-02,
        6.0000e+00, 2.9000e+01, 9.9870e-01, 2.8800e+00, 8.2000e-01,
        9.8000e+00, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.9000e-01,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 9.2000e-01,
        1.1700e+01,

In [ ]:
high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol,10:]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [ ]:
wines1=wines.reshape((12,1599))
wines1.shape

(12, 1599)