<a href="https://colab.research.google.com/github/bhavya5463/DA-LAB/blob/da-lab/NUMPY_EXAMPLES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. How to get 1, 2 or 3 dimension NumPy array?
import numpy as np
print("1 dimension array")
a=np.arange(3)
print(a)
print(a.ndim)
print("2 dimension array")
b=np.arange(9).reshape((3,3))
print(b)
print(b.ndim)
print("3 dimension array")
c=np.arange(12).reshape((2,2,3))
print(c)
print(c.ndim)

1 dimension array
[0 1 2]
1
2 dimension array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
3 dimension array
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


In [ ]:
#2.	How to resize NumPy array?
a=np.array([[1,2,3],[4,5,6]])
a.resize(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#3.	How to convert List or Tuple into NumPy array?
l=[1,2,3,4]
print(type(l))
a=np.asarray(l)
print(a)
print(type(a))

t=(1,4,3,7)
print(type(t))
b=np.asarray(t)
print(b)
print(type(b))

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'tuple'>
[1 4 3 7]
<class 'numpy.ndarray'>


In [ ]:
#4.How to create NumPy array using arange function?
a=np.arange(9).reshape((3,3))
print(a)

Object `function` not found.
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#5.	How to create NumPy arrays with linspace()?
a=np.linspace(0,100,5)
print(a)

b=np.linspace(25,50,2)
print(b)

[  0.  25.  50.  75. 100.]
[25. 50.]


In [ ]:
#6.	NumPy logspace array example
a=np.logspace(2,6,num=5,base=2)
print(a)

b=np.logspace(4,5,num=3)
print(b)

[ 4.  8. 16. 32. 64.]
[ 10000.          31622.77660168 100000.        ]


In [ ]:
#7.	NumPy Full array example
a=np.full([3,3],66,dtype=int)
print(a)

b=np.full([4,4],7)
print(b)

[[66 66 66]
 [66 66 66]
 [66 66 66]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#8. NumPy Eye array example
a=np.eye(2,k=1)
print(a)

b=np.eye(4,k=-1)
print(b)

c=np.eye(5,k=1)
print(c)

[[0. 1.]
 [0. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#9. NumPy generate random number array
#Description:1. The np.random.rand method, generates an array with random numbers that are uniformly distributed between 0 and 1.
a=np.random.rand(3,4)
print(a)

#2.The np.random.randn method, generates an array with random numbers that are normally distributed between 0 and 1.
b=np.random.randn(2,2)
print(b)

#3.The np.random.randint method, generates an array with random  numbers that are uniformly distributed between 0 and given integer.
c=np.random.randint(10,size=(3,3))
print(c)

[[0.04736947 0.2458409  0.69978098 0.03194819]
 [0.37615973 0.65590762 0.46968307 0.30112029]
 [0.42329413 0.44464338 0.85208656 0.21746927]]
[[-0.91577576 -0.71433887]
 [-1.2878843  -0.62654661]]
[[4 9 6]
 [7 0 3]
 [5 0 6]]


In [ ]:
#10.	NumPy Identity and Diagonal Array Example
#Note:The identity() function, generates square array with ones on the main diagonal whereas diag() function extract or construct diagonal array.
a=np.identity(4)
print(a)

b=np.diag(np.arange(2,8,2))
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [ ]:
#11.	NumPy Indexing in Multidimensional array
#Note: Indexing in a 3-Dimensional Array is based on syntax: array3d[L,M,N] where L is the first index, M is the row no. and N is the column no.
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
9


In [ ]:
#12.	NumPy Single Dimensional Slicing Examples
a=np.array([1,2,3,4,5])
print(a[4])

5


In [ ]:
#13.	Multidimensional Slicing in NumPy Array
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print("to select sub array")
print(a[0])
print("to select row")
print(a[0][1])
print("to select particular element")
print(a[0][1][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
to select sub array
[[1 2 3]
 [4 5 6]]
to select row
[4 5 6]
to select particular element
6


In [ ]:
#14.	Flips the order of the axes of an NumPy Array
#The transpose function transpose also exists as a method in ndarray and it permute the dimensions of an array. 
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
atrans=np.transpose(a)
print(a)
#The fliplr (flip left-right) and flipud (flip up-down) functions perform operations that are similar to the transpose and the shape of the output array is the same as the input. 
print("flip left right")
b=np.fliplr(a)
print(b)
print("flip up down")
c=np.flipud(a)
print(c)
#The fliplr flip an array in the left/right direction. The flipud flip an array in the up/down direction. The rot90 Rotate an array by 90 degrees in the plane specified by axes and the rotation direction is from the first towards the second axis.
print("rotate 90")
d=np.rot90(a)
print(d)

[[1 2]
 [3 4]
 [5 6]]
flip left right
[[2 1]
 [4 3]
 [6 5]]
flip up down
[[5 6]
 [3 4]
 [1 2]]
rotate 90
[[2 4 6]
 [1 3 5]]


In [ ]:
#15)Joining and Stacking of NumPy arrays
#NumPy uses the concept of stacking and provide a number of functions to perform: vertical stacking(row wise) using vstack(), horizontal stacking(column wise) using hstack() and depth wise stacking(along third axis) using dstack(). 
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
print(c)
d=np.vstack((a,b))
print(d)
e=np.dstack((a,b))
print(e)
f=np.append(a,b)
print(f)
g=np.concatenate((a,b))
print(g)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#16.	NumPy Elementary Mathematical Functions
#These mathematical functions takes a single array of any dimension as input and returns a new array of the same shape.
a=np.sin(30*np.pi/180)
print("sin value is:",a)
b=np.cos(60*np.pi/180)
print("cos is:",b)
c=np.tan(45)
print("tan value:",c)

d=np.arcsin(1)
print("sin inverse is:",d)
e=np.arccos(0.5)
print("cos inverse is:",e)
f=np.arctan(1)
print("tan inverse is:",f)

g=np.cosh(0)
print("hyperbolic fdunction:",g)
h=np.sinh(0)
print("sin hyperbolic is:",h)
i=np.tanh(1)
print("tan hyperbolic function is:",i)

j=np.arccosh(1)
print("inverse of cos hyperbolic function:",j)
in_array = [2, 1, 10, 100]  
arccosh_Values = np.arccosh(in_array)
print ("\nInverse hyperbolic Cosine values : \n", arccosh_Values)
in_array =np.array([0,-0.5])
arctanh_Values = np.arctanh(in_array)
print ("\nInverse hyperbolic Cosine values : \n", arctanh_Values)

x=np.sqrt([81,16,36])
print("squareroot of number is:",x)

y=np.exp([1,2,3])
print("exponential is:",y)

print("logarithms")
z=np.log([1,10])
print(z)
u=np.log2([2,4,8])
print(u)
v=np.log10([10,100,100000])
print(v)

sin value is: 0.49999999999999994
cos is: 0.5000000000000001
tan value: 1.6197751905438615
sin inverse is: 1.5707963267948966
cos inverse is: 1.0471975511965979
tan inverse is: 0.7853981633974483
hyperbolic fdunction: 1.0
sin hyperbolic is: 0.0
tan hyperbolic function is: 0.7615941559557649
inverse of cos hyperbolic function: 0.0

Inverse hyperbolic Cosine values : 
 [1.3169579  0.         2.99322285 5.29829237]

Inverse hyperbolic Cosine values : 
 [ 0.         -0.54930614]
squareroot of number is: [9. 4. 6.]
exponential is: [ 2.71828183  7.3890561  20.08553692]
logarithms
[0.         2.30258509]
[1. 2. 3.]
[1. 2. 5.]


In [ ]:
#17.	NumPy Element Wise Mathematical Operations
a=np.array([4,5,6])
b=np.array([1,2,3])
c=np.add(a,b)
print("addition is",c)
d=np.subtract(a,b)
print("subtraction is:",d)
e=np.multiply(a,b)
print("multiplication is:",e)
f=np.divide(a,b)
print("division is:",f)

g=np.power(a,b)
print("power is:",g)

h=np.remainder(a,b)
print("remainder is:",h)

i=np.reciprocal(a)
print("reciprocal is:",i)

c=np.array([-1,4,-6])
j=np.sign(c)
print("sign is:",j)
k=np.abs([-0.67,3.78])
print("absolute is:",k)

l=np.ceil([-1.5,-3.7,0.5,2.8])
print("ceil is:",l)
m=np.floor([-1.5,-3.7,0.5,2.8])
print("floor is:",m)

n=np.round([0.5,0.3,5.8,5.3])
print("round is :",n)

addition is [5 7 9]
subtraction is: [3 3 3]
multiplication is: [ 4 10 18]
division is: [4.  2.5 2. ]
power is: [  4  25 216]
remainder is: [0 1 0]
reciprocal is: [0 0 0]
sign is: [-1  1 -1]
absolute is: [0.67 3.78]
ceil is: [-1. -3.  1.  3.]
floor is: [-2. -4.  0.  2.]
round is : [0. 0. 6. 5.]


In [ ]:
#18.	NumPy Aggregate and Statistical Functions
a=np.array([1,2,3,4,5])
b=np.mean(a)
print("mean:",b)

c=np.std(a)
print("standard deviation :",c)

d=np.var(a)
print("variance :",d)

e=np.sum(a)
print("sum of elments :",e)

f=np.prod(a)
print("product :",f)

g=np.cumsum(a)
print("cummulative sum :",g)

h=np.cumprod(a)
print("cummulative product:",h)

i=np.min(a)
j=np.max(a)
print("minimum and maximum value of an array:",i,j)

k=np.argmin(a)
l=np.argmax(a)
print("indices of the minimum and maximum value:",k,l)

m=np.array([[1,0],[3,4]])
n=np.all(m,axis=0)
print(n)
o=np.all(m,axis=1)
print(o)

t=np.array([1,3,0,5])
p=np.any(t)
print(p)

mean: 3.0
standard deviation : 1.4142135623730951
variance : 2.0
sum of elments : 15
product : 120
cummulative sum : [ 1  3  6 10 15]
cummulative product: [  1   2   6  24 120]
minimum and maximum value of an array: 1 5
indices of the minimum and maximum value: 0 4
[ True False]
[False  True]
True


In [ ]:
#19.	NumPy Example of Where function
#Description:The where() function is used to chooses values from arrays depending on the value of a specific condition.
a=np.arange(10)
b=np.where(a>5,a,a*10)
print(b)

c=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.where(c>3,c,0)

[ 0 10 20 30 40 50  6  7  8  9]


array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#20.NumPy Example of Select function
#Description:The select() function return an array drawn from elements in choice list, depending on conditions.
a=np.arange(9)
condlist=[a>=5,a<5]
choicelist=[a,a**2]
b=np.select(condlist,choicelist)
print(b)

[ 0  1  4  9 16  5  6  7  8]


In [ ]:
#21.	NumPy Logical operations for selectively picking values from an array depending on a given condition
#Note:logical_or computes the truth value of x1 OR x2 element-wise. 
#logical_and computes the truth value of x1 AND x2 element-wise.
#logical_or computes the truth value of NOT x element-wise.
x=np.arange(4)
a=np.logical_and(x>1,x<4)
print(a)

b=np.logical_or(x>1,x<4)
print(b)

c=np.logical_not(x>1)
print(c)

[False False  True  True]
[ True  True  True  True]
[ True  True False False]


In [ ]:
#22.	NumPy example of Standard Set Operations
#Note:The standard set operations union (array of values that are in either of the two input arrays), intersection (unique values that are in both of the input arrays), and difference (unique values in array1 that are not in array2) are provided by np.union1d(), np.intersect1d(), and np.setdiff1d(), respectively.
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.union1d(a,b)
print(c)
d=np.intersect1d(a,b)
print(d)
e=np.setdiff1d(b,a)
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[]
[ 7  8  9 10 11 12]
